name: Push to other remote
on: 
  pull_request:
    branches :
      - main
      - develop

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        token: ${{ secrets.REMOTE_TOKEN }}
        fetch-depth: 0
        
    - name: List local branches
      run: git branch

    - name: Setup Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
    
    - name: Check remote URL
      run: |
        echo "Remote URL is ${{ secrets.REMOTE_INNOVAWEB }}"
        if [ -z "${{ secrets.REMOTE_INNOVAWEB }}" ]; then
          echo "REMOTE_URL is missing"
          exit 1
        fi

    - name: Debug remote config
      run: git remote -v

    - name: Stash uncommitted changes
      run: git stash

    - name: Checkout target branch of PR
      run: |
        git fetch
        git checkout ${{ github.base_ref }}

    - name: Apply stash and commit
      run: |
        git stash apply || true
        git add .
        git commit -m "Apply stash via GitHub Actions" || true
        
    - name: Pull from remote before push
      run: git pull ${{ secrets.REMOTE_INNOVAWEB }} ${{ github.base_ref }}
      
    - name: Push changes
      run: |
        echo "Remote URL : git push ${{ secrets.REMOTE_INNOVAWEB }} HEAD:${{ github.base_ref }}" |
        git push ${{ secrets.REMOTE_INNOVAWEB }} ${{ github.base_ref }}
