name: Push to other remote
on: 
  pull_request:
    types: [opened, synchronize]
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Check remote URL
      run: |
        echo "Remote URL is ${{ secrets.REMOTE_INNOVAWEB }}"
        if [ -z "${{ secrets.REMOTE_INNOVAWEB }}" ]; then
          echo "REMOTE_URL is missing"
          exit 1
        fi
    
    - name: Setup Git
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
             
    - name: Checkout repository
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0

    - name: Push changes
      run: |
        echo "Remote URL : git push ${{ secrets.REMOTE_INNOVAWEB }} HEAD:${{ github.base_ref }}" |
        git push ${{ secrets.REMOTE_INNOVAWEB }} HEAD:${{ github.base_ref }}
