name: Push to Remote
on:
  pull_request:
    branches:    
      - main
      - develop

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with: 
        token: ${{ secrets.REMOTE_TOKEN }}
        fetch-depth: 0
        
    - name: Configure Git  
      run: |
        git config user.name "Actions"
        git config user.email "actions@github.com"
        
    - name: Check remote URL
      run: |
        echo "Remote URL is ${{ secrets.REMOTE_INNOVAWEB }}"
        if [ -z "${{ secrets.REMOTE_INNOVAWEB }}" ]; then
          echo "Missing remote URL" 
          exit 1
        fi
    
    - name: Add remote  
      run: |
        git remote add remote_repo ${{ secrets.REMOTE_INNOVAWEB }}
    
    - name: Fetch latest changes
      run: |
        git fetch remote_repo

    - name: Pull changes  
      run: |
        git pull remote_repo main
    
    - name: Push changes
      run: |
        git push remote_repo HEAD:${{github.base_ref}}
