name: Push to other remote based on PR target branch

on: 
  pull_request:
    types: [opened,synchronize]
    
env:
  REMOTE_INNOVAWEB: ${{secrets.REMOTE_INNOVAWEB}}

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configure Git  
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Add remote origin
      run: |  
        if ! git remote | grep -q origin; then
          git remote add origin https://github.com/${GITHUB_REPOSITORY}.git
        fi

    - name: Add remote REMOTE_INNOVAWEB
      run: |
        git remote add REMOTE_INNOVAWEB ${{env.REMOTE_INNOVAWEB}}

    - name: Push to REMOTE_INNOVAWEB
      run: |
        git push REMOTE_INNOVAWEB HEAD:${GITHUB_BASE_REF}
